[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "piriview-core"
version = "0.1.0.dev0"
description = "An open-source workstation for medical image visualization, segmentation, and quantitative analysis."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Reza Piri"}
]

dependencies = [
    "PySide6>=6.7"
]

[project.urls]
Repository = "https://github.com/drrezapiri/PiriView-Core"
Issues = "https://github.com/drrezapiri/PiriView-Core/issues"

[tool.setuptools.packages.find]
where = ["src"]
